In [1]:
#table logika AND 2 input

"""
x1    x2    y
1     1     1
1     0     0
0     0     0
0     0     0
"""

'\nx1    x2    y\n1     1     1\n1     0     0\n0     0     0\n0     0     0\n'

In [2]:
#machine learning

import keras
import numpy as np

#model
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

#model compile
model.compile(optimizer='sgd', loss='mean_squared_error')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [3]:
#set data
xs = np.array([[1, 1], [1, 0], [0, 1], [0, 0]], dtype=int)
ys = np.array([1, 0, 0, 0], dtype=int)

In [4]:
#tampilkan arsitektur awal
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
#cek bobot model awal
weights = model.get_weights()
weights

[array([[1.3226331],
        [1.412258 ]], dtype=float32),
 array([0.], dtype=float32)]

In [6]:
#training
model.fit(xs, ys, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step - loss: 1.6884
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - loss: 1.5919
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 1.5014
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 1.4165
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 1.3369
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1.2623
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 1.1923
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 1.1267
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 1.0652
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1.0075
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.9533
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.9026
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.8550
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.8103
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 0.7684


In [8]:
#test
data = [1,1]
answer = model.predict(np.array([data]))
print(answer)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
[[0.7648196]]


In [9]:
weights = model.get_weights()
weights

[array([[0.51791084],
        [0.51850736]], dtype=float32),
 array([-0.27159855], dtype=float32)]

In [11]:
#table data
w1 = 2
w2 = 4

"""

x1    x2    y
2     3     16
4     1     12
5     4     28
7     5     34
8     2     24
2     1     8
4     9     44
8     2     24
7     1     18
6     5     32
1     1     6
3
"""

'\n\nx1    x2    y\n2     3     16\n4     1     12\n5     4     28\n7     5     34\n8     2     24\n2     1     8\n4     9     44\n8     2     24\n7     1     18\n6     5     32\n1     1     6\n3\n'

In [12]:
#model
model2 = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

#model compile
model2.compile(optimizer='sgd', loss='mean_squared_error')

#set data
xs = np.array([[2, 3], [4, 1], [5, 4], [7, 5], [8, 2], [2, 1], [4, 9], [8, 2], [7, 1], [6, 5], [1, 1], [3, 2]])
ys = np.array([16, 12, 28, 34, 24, 8, 44, 24, 18, 32, 6, 14], dtype=int)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
#cek bobot model awal
weights = model2.get_weights()
weights

[array([[-1.1703812],
        [-1.2688282]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
#training
model2.fit(xs, ys, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 459ms/step - loss: 1191.1598
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 91.4796
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 27.9851
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 20.4645
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 16.6733
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 13.6981
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 11.2715
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 9.2873
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 7.6646
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 6.3374
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 5.2519
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4.3641
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 3.6380
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 3.0441
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2

In [22]:
#test
data = [1,3]
answer = model2.predict(np.array([data]))
print(answer)

#seharusnya 1*2 + 3*4 = 14

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
[[14.172548]]


In [20]:
weigths =model2.get_weights()
weigths

[array([[1.9997483],
        [4.028435 ]], dtype=float32),
 array([0.08749413], dtype=float32)]